kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: grafana
resources:
  - ./namespace.yaml
  - ./rbac.yaml
  - ./secret.yaml
  - ./grafana.yaml
  - ./datasource.yaml
  - ./route.yaml
  - ./dashboards
